# What is Numpy ?

Numpy is a Linear Algebra Library for Python

# How to use ?

In [1]:
import numpy as np

# Numpy Arrays

Numpy arrays are used to store data in numpy. They are of two types: Vectors(1-D Array) and Matrices(2-D Array)

## Creating Numpy Array

### From a Python List

In [6]:
my_list = [1, 2, 3, 4, 5]
my_list

[1, 2, 3, 4, 5]

In [7]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [8]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built In Methods

### arange(start, stop, step)
Returns evenly spaced values in the given interval

In [13]:
np.arange(1, 15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
np.arange(1, 15, 2)

array([ 1,  3,  5,  7,  9, 11, 13])

### zeros and ones
Generate array of Zero and Ones

In [15]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [16]:
np.zeros((3, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [17]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [18]:
np.ones((3, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### linspace
Returns evenly spaced numbers in a given interval

In [21]:
np.linspace(0, 1, 3)

array([ 0. ,  0.5,  1. ])

In [22]:
np.linspace(0, 10, 7)

array([  0.        ,   1.66666667,   3.33333333,   5.        ,
         6.66666667,   8.33333333,  10.        ])

### eye
Creates a Identity Matrix

In [23]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

## Random
Create random number arrays
### rand
Creates a random array

In [24]:
np.random.rand(2)

array([ 0.801894  ,  0.19760887])

In [25]:
np.random.rand(2, 2)

array([[ 0.37913217,  0.00427112],
       [ 0.43566072,  0.76720039]])

### randn
Creates a random array from "standard normal" distribution.

A normal distribution is a distribution where the values are more likely to occur near the mean value.

A standard normal distribution is just a normal distribution where the average value is 0, and the variance is 1.

In [26]:
np.random.randn(3)

array([-0.15946431, -1.28703099,  0.32065418])

In [27]:
np.random.rand(3, 3)

array([[ 0.26960204,  0.70329842,  0.85784382],
       [ 0.65841488,  0.05639503,  0.96966712],
       [ 0.74048892,  0.19346153,  0.72313835]])

### randint
Returns random integer from the given range low(inclusive) to high(exculsive)

In [28]:
np.random.randint(1, 10)

9

In [29]:
np.random.randint(1, 10, 5)

array([9, 5, 3, 3, 3])

## Array Attributes and Methods of Array
### arange
Return the array from start(inclusive) to end(exclusive)

In [31]:
my_array = np.arange(10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
my_array = np.arange(5, 15)
my_array

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### reshape
Returns the same data with new shape

In [33]:
my_array.reshape(5, 2)

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

### max
Returns maximum value

In [35]:
my_array.max()

14

### min
Returns minimum value

In [36]:
my_array.min()

5

### argmax
Index of maximum value

In [37]:
my_array.argmax()

9

### argmin
Index of minimum value

In [39]:
my_array.argmin()

0

## shape
Shape is a array attribute not method

In [40]:
my_array.shape

(10,)

In [41]:
my_array.reshape(2, 5)

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [42]:
my_array.reshape(2, 5).shape

(2, 5)

## dtype
Array attribute that tells the data type of array

In [43]:
my_array.dtype

dtype('int64')

# Happy Learning !!